version: '3'
services:
  envoy:
    image: envoyproxy/envoy-dev
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./pkg/envoy_filter_playground_bg.wasm:/etc/filter.wasm
      - ./pkg/envoy_service_playground_bg.wasm:/etc/service.wasm
      - ./envoy.yaml:/etc/envoy/envoy.yaml
